"use client";

import { motion, useScroll, useSpring } from "framer-motion";
import { ArrowDown, ArrowUpRight, BriefcaseBusiness, Code2, Download, ExternalLink, Github, GraduationCap, Linkedin, Mail, Menu, TerminalSquare, X } from "lucide-react";
import { useEffect, useState } from "react";
import { education, experience, leadership, projects, skillGroups, socials } from "@/lib/portfolio-data";

const navItems = [["01 Profile", "#about"], ["02 Work", "#work"], ["03 Experience", "#experience"], ["04 Stack", "#skills"], ["05 Contact", "#contact"]] as const;
const reveal = { hidden: { opacity: 0, y: 20 }, show: { opacity: 1, y: 0 } };

function Boot() {
  const [ready, setReady] = useState(false);
  useEffect(() => { if (sessionStorage.getItem("mg-signal")) setReady(true); else { sessionStorage.setItem("mg-signal", "1"); const timer = window.setTimeout(() => setReady(true), 900); return () => window.clearTimeout(timer); } }, []);
  if (ready) return null;
  return <div className="boot-screen"><div className="boot-mark"><span className="signal-dot" /> SIGNAL ACQUIRED</div><p>initializing interface...</p><div className="boot-line"><span /></div></div>;
}

function Trace() { const { scrollYProgress } = useScroll(); const scale = useSpring(scrollYProgress, { stiffness: 100, damping: 30 }); return <div className="trace" aria-hidden><motion.div className="trace-pulse" style={{ scaleY: scale }} /><span className="trace-node node-a" /><span className="trace-node node-b" /><span className="trace-node node-c" /></div>; }
function SectionTitle({ eyebrow, title, copy }: { eyebrow: string; title: string; copy?: string }) { return <motion.div variants={reveal} initial="hidden" whileInView="show" viewport={{ once: true, margin: "-70px" }} className="section-title"><p>{eyebrow}</p><h2>{title}</h2>{copy && <span>{copy}</span>}</motion.div>; }

function Navbar() { const [open, setOpen] = useState(false); const [active, setActive] = useState("#about"); useEffect(() => { const obs = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActive(`#${entry.target.id}`)), { rootMargin: "-35% 0px -55%" }); navItems.forEach(([, href]) => { const el = document.querySelector(href); if (el) obs.observe(el); }); return () => obs.disconnect(); }, []); return <header className="nav-wrap"><div className="nav"><a href="#top" className="wordmark" aria-label="Go to top"><b>MG</b><span>MUKUND GARG</span></a><nav aria-label="Primary navigation">{navItems.map(([label, href]) => <a key={href} href={href} className={active === href ? "active" : ""}>{label}</a>)}</nav><div className="nav-actions"><a href={socials.resume} target="_blank" rel="noreferrer" className="resume"><Download size={14} /> Resume</a><button onClick={() => setOpen(!open)} aria-label="Toggle navigation" aria-expanded={open}>{open ? <X size={17} /> : <Menu size={17} />}</button></div></div>{open && <div className="mobile-nav">{navItems.map(([label, href]) => <a key={href} href={href} onClick={() => setOpen(false)}>{label}</a>)}</div>}</header>; }

function Waveform() { return <svg className="waveform" viewBox="0 0 700 180" role="img" aria-label="Animated signal waveform settling into the Mukund Garg wordmark"><path d="M0 92h80l12-42 18 82 16-58 16 36 20-18 22 0 20-4 18 3 22-2 20 1 20-1 20 2 22-2 20 1 20-1 20 1 20-1 20 1 20-1 20 2 20-2 20 1 20-1 20 1 20-1 20 1 20-1 22 2 20-2 24 1" fill="none" stroke="currentColor" strokeWidth="2" className="wave-path" /></svg>; }
function Hero() { return <section id="top" className="hero"><div className="hero-grid" /><div className="hero-copy"><div className="status"><span className="signal-dot" /> OPEN TO TECH INTERNSHIPS</div><Waveform /><p className="hero-name">MUKUND GARG</p><h1>I build AI systems<br /><em>that ship.</em></h1><p className="hero-description">Second-year ECE student focused on applied ML, backend systems, automation, computer vision, and turning technical ideas into working products.</p><div className="hero-links"><a className="button-primary" href="#work">View my work <ArrowDown size={15} /></a><a className="button-quiet" href={socials.email}><Mail size={15} /> Contact me</a></div><p className="discipline">ECE <i>×</i> AI/ML <i>×</i> BACKEND</p></div><div className="readout"><div className="readout-head"><span>PROFILE.READOUT</span><TerminalSquare size={17} /></div>{[["FOCUS", "AI/ML · Backend · Automation"], ["LOCATION", "New Delhi, India"], ["EDUCATION", "MSIT · B.Tech ECE"], ["CURRENT", "Building applied AI systems"]].map(([a, b]) => <div className="readout-row" key={a}><small>{a}</small><strong>{b}</strong></div>)}<div className="socials"><a href={socials.github} target="_blank" rel="noreferrer" aria-label="GitHub"><Github size={16} /></a><a href={socials.linkedin} target="_blank" rel="noreferrer" aria-label="LinkedIn"><Linkedin size={16} /></a><a href={socials.email} aria-label="Email"><Mail size={16} /></a></div></div></section>; }

function About() { return <section id="about" className="section"><SectionTitle eyebrow="01 / PROFILE" title="Software, ML, and systems thinking in one profile." copy="My projects sit at the intersection of applied AI and useful software — from on-device vision to workflow automation and financial-analysis tools." /><div className="profile-grid"><div className="system-record large"><small>FIELD NOTE / 001</small><h3>I like problems where code removes friction.</h3><p>MailPilot came directly from repetitive outreach work at Iqlipse. StockSense combines API design, LLMs, and OpenCV. My ISL app pushed me into real-time, offline inference on Android. I learn fastest by connecting theory to something that works end-to-end.</p><div className="tags">{["Applied AI", "Backend Systems", "Automation", "Computer Vision"].map((x) => <span key={x}>{x}</span>)}</div></div><div className="system-record"><small>ACADEMIC SIGNAL</small><b className="score">8.82<span>/10</span></b><p>First-year CGPA · B.Tech ECE · MSIT</p></div><div className="system-record"><small>OUTPUT RANGE</small><h3>32 gesture outputs</h3><p>Offline ISL recognition: 26 alphabet signs + 6 fixed words.</p></div><div className="system-record wide"><small>CORE STACK</small><div className="tags">{["FastAPI", "PyTorch", "OpenCV", "Scikit-learn", "Docker", "Pydantic", "Gemini", "Gmail API"].map((x) => <span key={x}>{x}</span>)}</div></div></div></section>; }

function Diagram({ index }: { index: number }) { if (index === 0) return <div className="diagram pipeline"><span>INGEST</span><i>→</i><span>PERSONALIZE</span><i>→</i><span>SCHEDULE</span><i>→</i><span>THREAD</span><b>GMAIL API</b></div>; if (index === 1) return <div className="diagram chart"><svg viewBox="0 0 300 100"><path d="M0 76 C25 55 37 65 58 48 S86 75 106 45 S140 47 156 35 S183 57 205 29 S237 39 254 15 S280 31 300 10" fill="none" stroke="currentColor" strokeWidth="2" /><path d="M0 91h300M0 60h300M0 30h300" stroke="currentColor" opacity=".15" /></svg><span>CONFIDENCE 0.94 · PATTERN DETECTED</span></div>; return <div className="diagram isl"><span>CAMERA</span><i>→</i><span>LANDMARKS</span><i>→</i><span>GESTURE</span><i>→</i><strong>TEXT</strong></div>; }
function Projects() { return <section id="work" className="section"><SectionTitle eyebrow="02 / WORK" title="Projects with a reason to exist." copy="I prefer projects that solve a concrete problem and force me to connect several layers of the stack." /><div className="projects">{projects.map((project, index) => <motion.article variants={reveal} initial="hidden" whileInView="show" viewport={{ once: true }} key={project.title} className="project"><div className="project-top"><span>{project.kicker}</span><small>0{index + 1} / 03</small></div><h3>{project.title}</h3><Diagram index={index} /><p>{project.description}</p><div className="metrics">{project.metrics.map((m) => <span key={m}>{m}</span>)}</div><div className="stack">{project.stack.map((s) => <span key={s}>{s}</span>)}</div><div className="project-links"><a href={project.github} target="_blank" rel="noreferrer"><Github size={14} /> Source</a>{project.live && <a href={project.live} target="_blank" rel="noreferrer"><ExternalLink size={14} /> Live</a>}</div></motion.article>)}</div></section>; }

function Experience() { return <section id="experience" className="section"><SectionTitle eyebrow="03 / EXPERIENCE" title="From operations friction to software automation." /><div className="experience-grid"><div className="system-record experience-record"><div className="record-title"><BriefcaseBusiness size={16} /><span>{experience.company}</span><small>{experience.period}</small></div><h3>{experience.role}</h3><p className="muted">{experience.location}</p><ul>{experience.bullets.map((b) => <li key={b}>{b}</li>)}</ul></div><div className="education-list">{education.map((item) => <div className="system-record" key={item.school}><div className="record-title"><GraduationCap size={16} /><small>{item.period}</small></div><h3>{item.school}</h3><p>{item.degree}</p><b>{item.meta}</b></div>)}</div></div><div className="leadership"><p className="eyebrow">LEADERSHIP / ACTIVE</p>{leadership.map((item) => <div className="leadership-row" key={item.org}><strong>{item.role}</strong><span>{item.org}</span><small>{item.period}</small></div>)}</div></section>; }

function Skills() { const groups: [string, readonly string[]][] = [["Machine Intelligence", [...skillGroups[0].items, ...skillGroups[1].items, ...skillGroups[2].items]], ["Systems", [...skillGroups[3].items, ...skillGroups[5].items]], ["Perception", skillGroups[4].items]]; return <section id="skills" className="section"><SectionTitle eyebrow="04 / STACK" title="A broad toolkit, grouped by how I use it." copy="These categories fold together the ML, deep learning, NLP, OpenCV, and FastAPI material I have studied and applied." /><div className="capability-grid">{groups.map(([label, items], index) => <div className="capability" key={label}><div><span>0{index + 1}</span><Code2 size={17} /><h3>{label}</h3></div><p>{(items as readonly string[]).join(" · ")}</p></div>)}</div></section>; }
function Contact() { return <section id="contact" className="contact section"><p className="eyebrow">05 / CONTACT</p><h2>END OF TRANSMISSION</h2><p>Have a technical problem worth building around?</p><span>I&apos;m currently looking for tech internship opportunities across AI/ML, backend, automation, and software engineering.</span><a className="button-primary" href={socials.email}>Email me <ArrowUpRight size={15} /></a></section>; }
function Footer() { return <footer><span>© 2026 Mukund Garg</span><span>Signal stable · New Delhi, India</span></footer>; }
export function Portfolio() { return <><Boot /><Trace /><Navbar /><main><Hero /><About /><Projects /><Experience /><Skills /><Contact /></main><Footer /></>; }
