"use client";

import { motion, useScroll, useSpring } from "framer-motion";
import { ArrowDown, ArrowUpRight, BriefcaseBusiness, Code2, Download, ExternalLink, Github, GraduationCap, Linkedin, Mail, Menu, Pin, Terminal, X } from "lucide-react";
import { useEffect, useState } from "react";
import { education, experience, leadership, projects, skillGroups, socials } from "@/lib/portfolio-data";

const navItems = [["Home", "#top"], ["Profile", "#about"], ["Builds", "#work"], ["Experience", "#experience"], ["Stack", "#skills"]] as const;
const reveal = { hidden: { opacity: 0, y: 18 }, show: { opacity: 1, y: 0 } };

function Boot() {
  const [ready, setReady] = useState(false);
  useEffect(() => { const timer = window.setTimeout(() => setReady(true), 650); return () => window.clearTimeout(timer); }, []);
  if (ready) return null;
  return <div className="boot-screen"><div className="boot-mark"><span className="signal-dot" /> BUILD FEED</div><p>loading Mukund&apos;s systems...</p><div className="boot-line"><span /></div></div>;
}
function Trace() { const { scrollYProgress } = useScroll(); const scale = useSpring(scrollYProgress, { stiffness: 100, damping: 30 }); return <div className="trace" aria-hidden><motion.div className="trace-pulse" style={{ scaleY: scale }} /></div>; }
function Navbar() { const [open, setOpen] = useState(false); const [active, setActive] = useState("#top"); useEffect(() => { const obs = new IntersectionObserver((entries) => entries.forEach((e) => e.isIntersecting && setActive(`#${e.target.id}`)), { rootMargin: "-35% 0px -55%" }); navItems.forEach(([, href]) => { const el = document.querySelector(href); if (el) obs.observe(el); }); return () => obs.disconnect(); }, []); return <aside className="left-rail"><a className="brand" href="#top"><b>MG</b><span>MUKUND<br />/ BUILD FEED</span></a><button className="mobile-menu" onClick={() => setOpen(!open)} aria-label="Toggle navigation" aria-expanded={open}>{open ? <X /> : <Menu />}</button><nav className={open ? "nav-open" : ""} aria-label="Primary navigation">{navItems.map(([label, href]) => <a key={href} href={href} className={active === href ? "active" : ""} onClick={() => setOpen(false)}><span>{active === href ? "●" : "○"}</span>{label}</a>)}</nav><div className="rail-bottom"><span className="status"><i /> AVAILABLE FOR INTERNSHIPS</span><a className="resume-link" href={socials.resume} target="_blank" rel="noreferrer"><Download /> Resume</a></div></aside>; }
function RightRail() { return <aside className="right-rail"><div className="rail-card"><p className="eyebrow">NOW BUILDING</p><h3>Applied AI systems that work in the real world.</h3><div className="signal-row"><i /><span>Signal stable</span><small>NEW DELHI, IN</small></div></div><div className="rail-card"><p className="eyebrow">FOCUS AREAS</p><div className="focus-list">{["AI / MACHINE LEARNING", "BACKEND ENGINEERING", "COMPUTER VISION", "AUTOMATION"].map((x) => <span key={x}>{x}<ArrowUpRight /></span>)}</div></div><div className="rail-card contact-card"><p className="eyebrow">OPEN CHANNEL</p><p>Have a technical problem worth building around?</p><a href={socials.email}>gargmukund774@gmail.com <ArrowUpRight /></a></div></aside>; }
function ProfileHeader() { return <section className="profile-header" id="top"><div className="avatar">MG</div><div className="profile-main"><div className="profile-name"><h1>MUKUND GARG</h1><span>ECE × AI/ML × BACKEND</span></div><p>Building systems at the intersection of AI, backend engineering and real-world automation.</p><div className="profile-meta"><span>New Delhi, India</span><span>MSIT · B.Tech ECE</span><span>Open to tech internships</span></div></div><a className="profile-action" href={socials.email}>Contact <ArrowUpRight /></a></section>; }
function Composer() { return <div className="composer"><div className="avatar small">MG</div><div><p className="composer-placeholder">What I&apos;m building, learning, or shipping...</p><div className="composer-actions"><span><Terminal /> ENGINEERING NOTES</span><a href="#work">VIEW SELECTED BUILDS <ArrowUpRight /></a></div></div></div>; }
function SectionLabel({ children }: { children: React.ReactNode }) { return <div className="section-label"><span>{children}</span><i /></div>; }
function Diagram({ index }: { index: number }) { if (index === 0) return <div className="diagram pipeline">{["INGEST", "PERSONALIZE", "SCHEDULE", "THREAD"].map((x, i) => <span key={x}>{x}{i < 3 && <b>→</b>}</span>)}<small>GMAIL API</small></div>; if (index === 1) return <div className="diagram chart"><svg viewBox="0 0 320 88" role="img" aria-label="Stock pattern confidence chart"><path d="M0 70 C28 50 40 66 66 45 S98 70 126 41 S160 50 180 30 S218 54 240 25 S280 40 320 8" fill="none" stroke="currentColor" strokeWidth="2" /><path d="M0 76h320M0 44h320M0 12h320" stroke="currentColor" opacity=".18" /></svg><small>CONFIDENCE 0.94 · PATTERN DETECTED</small></div>; return <div className="diagram pipeline">{["CAMERA", "LANDMARKS", "GESTURE", "TEXT"].map((x, i) => <span key={x}>{x}{i < 3 && <b>→</b>}</span>)}</div>; }
function ProjectPost({ project, index }: { project: (typeof projects)[number]; index: number }) { const [open, setOpen] = useState(false); return <motion.article className="post" variants={reveal} initial="hidden" whileInView="show" viewport={{ once: true }}><div className="post-head"><div className="avatar small">MG</div><div><strong>Mukund Garg</strong><span>@MukundGarg · BUILD LOG</span></div><span className="post-index">0{index + 1}</span></div><div className="post-copy"><div className="project-kicker">{project.kicker}</div><h3>{project.title}</h3><p>{project.description}</p></div><Diagram index={index} /><div className="tag-row">{project.metrics.map((m) => <span key={m}>{m}</span>)}</div><div className="stack-row">{project.stack.map((s) => <span key={s}>{s}</span>)}</div><div className="post-footer"><a href={project.github} target="_blank" rel="noreferrer"><Github /> Source</a>{project.live && <a href={project.live} target="_blank" rel="noreferrer"><ExternalLink /> Live system</a>}{index === 0 && <button onClick={() => setOpen(!open)} aria-expanded={open}>{open ? "Collapse thread" : "Read build thread"} <ArrowDown /></button>}</div>{open && <div className="thread"><div><Pin /><strong>Why I built this</strong></div><p>MailPilot came directly from repetitive outreach work at Iqlipse. After identifying reliability limits in the existing Mailmeteor workflow, I built a local system for personalized campaigns, scheduling, threaded follow-ups, reply detection, and Sheets sync.</p><div className="thread-note">The interesting part was not sending an email. It was making the workflow dependable.</div></div>}</motion.article>; }
function Builds() { return <section id="work"><SectionLabel>SELECTED SYSTEMS / 03</SectionLabel><div className="feed-intro"><h2>Projects with a<br /><em>reason to exist.</em></h2><p>I prefer projects that solve a concrete problem and force me to connect several layers of the stack.</p></div>{projects.map((p, i) => <ProjectPost key={p.title} project={p} index={i} />)}</section>; }
function Profile() { return <section id="about"><SectionLabel>PROFILE / FIELD NOTE</SectionLabel><article className="post profile-post"><p className="eyebrow">SIGNAL → DATA → MODELS → SYSTEMS → OUTPUTS</p><h2>Software, ML, and systems thinking in one profile.</h2><p>My work sits at the intersection of applied AI and useful software — from on-device vision to workflow automation and financial-analysis tools. I learn fastest by connecting theory to something that works end-to-end.</p><div className="stat-strip"><div><strong>8.82</strong><span>FIRST-YEAR CGPA / 10</span></div><div><strong>32</strong><span>ISL GESTURE OUTPUTS</span></div><div><strong>3</strong><span>PRIMARY SYSTEMS</span></div></div></article></section>; }
function Experience() { return <section id="experience"><SectionLabel>EXPERIENCE / EDUCATION</SectionLabel><article className="post"><div className="post-head"><div className="icon-box"><BriefcaseBusiness /></div><div><strong>{experience.role}</strong><span>{experience.company} · {experience.period}</span></div></div><p className="role-location">{experience.location}</p><ul className="bullet-list">{experience.bullets.map((b) => <li key={b}>{b}</li>)}</ul></article><div className="education-grid">{education.map((item) => <article className="post" key={item.school}><div className="post-head"><div className="icon-box"><GraduationCap /></div><div><strong>{item.school}</strong><span>{item.period}</span></div></div><p>{item.degree}</p><b className="accent-text">{item.meta}</b></article>)}</div><div className="leadership"><p className="eyebrow">LEADERSHIP / ACTIVE</p>{leadership.map((item) => <div key={item.org}><strong>{item.role}</strong><span>{item.org}</span><small>{item.period}</small></div>)}</div></section>; }
function Skills() { return <section id="skills"><SectionLabel>CAPABILITY MAP / STACK</SectionLabel><div className="capability-grid">{[["Machine intelligence", [...skillGroups[0].items, ...skillGroups[1].items, ...skillGroups[2].items]], ["Systems", [...skillGroups[3].items, ...skillGroups[5].items]], ["Perception", skillGroups[4].items]].map(([label, items], i) => <article className="post capability" key={label as string}><div className="cap-title"><Code2 /><h3>{label as string}</h3></div><p>{(items as string[]).join(" · ")}</p><span className="cap-index">0{i + 1}</span></article>)}</div></section>; }
function Footer() { return <section id="contact" className="end-feed"><div className="end-mark">MG</div><p className="eyebrow">END OF FEED</p><h2>Have a technical problem<br /><em>worth building around?</em></h2><a className="profile-action" href={socials.email}>Open channel <ArrowUpRight /></a><footer><span>© 2026 Mukund Garg</span><span>Signal stable · New Delhi, India</span><div><a href={socials.github}><Github /></a><a href={socials.linkedin}><Linkedin /></a><a href={socials.email}><Mail /></a></div></footer></section>; }
export function Portfolio() { return <><Boot /><Trace /><div className="feed-shell"><Navbar /><main className="feed-main"><ProfileHeader /><Composer /><Profile /><Builds /><Experience /><Skills /><Footer /></main><RightRail /></div></>; }
