"use client";

import { motion, useScroll, useSpring } from "framer-motion";
import { ArrowDown, ArrowUpRight, BriefcaseBusiness, Code2, Download, ExternalLink, Github, GraduationCap, Linkedin, Mail, Menu, Pin, X } from "lucide-react";
import { useEffect, useState } from "react";
import { education, experience, leadership, projects, skillGroups, socials } from "@/lib/portfolio-data";

const navItems = [["Profile", "#about"], ["Systems", "#work"], ["Experience", "#experience"], ["Education", "#education"], ["Contact", "#contact"]] as const;
const reveal = { hidden: { opacity: 0, y: 20 }, show: { opacity: 1, y: 0 } };

function Boot() { const [ready, setReady] = useState(false); useEffect(() => { const t = window.setTimeout(() => setReady(true), 700); return () => window.clearTimeout(t); }, []); if (ready) return null; return <div className="boot-screen"><div className="boot-mark"><span className="signal-dot" /> NEURAL PORTFOLIO</div><p>mapping data to systems...</p><div className="boot-line"><span /></div></div>; }
function Trace() { const { scrollYProgress } = useScroll(); const scale = useSpring(scrollYProgress, { stiffness: 100, damping: 30 }); return <div className="trace" aria-hidden><motion.div className="trace-pulse" style={{ scaleY: scale }} /></div>; }
function Navbar() { const [open, setOpen] = useState(false); const [active, setActive] = useState("#about"); useEffect(() => { const obs = new IntersectionObserver((entries) => entries.forEach((e) => e.isIntersecting && setActive(`#${e.target.id}`)), { rootMargin: "-35% 0px -55%" }); navItems.forEach(([, href]) => { const el = document.querySelector(href); if (el) obs.observe(el); }); return () => obs.disconnect(); }, []); return <header className="top-nav"><a className="brand" href="#top"><b>MG</b><span>MUKUND GARG</span></a><nav className={open ? "nav-open" : ""}>{navItems.map(([label, href], i) => <a key={href} href={href} className={active === href ? "active" : ""} onClick={() => setOpen(false)}><small>0{i + 1}</small>{label}</a>)}</nav><button className="mobile-menu" onClick={() => setOpen(!open)} aria-label="Toggle navigation" aria-expanded={open}>{open ? <X /> : <Menu />}</button></header>; }
function Network() { const [active, setActive] = useState(1); const nodes = [[92, 104], [92, 184], [92, 264], [92, 344], [270, 76], [270, 146], [270, 218], [270, 290], [270, 360], [448, 112], [448, 198], [448, 286], [620, 155], [620, 250]]; const edges = [[0,4],[0,5],[1,4],[1,6],[1,7],[2,5],[2,7],[2,8],[3,7],[3,8],[4,9],[4,10],[5,9],[5,10],[6,10],[6,11],[7,10],[7,11],[8,11],[9,12],[10,12],[10,13],[11,13]]; return <div className="network-wrap"><svg className="network" viewBox="0 0 710 430" role="img" aria-label="Interactive neural network with input, hidden and output layers">{edges.map(([a,b], i) => <path key={`${a}-${b}`} className={active === i % 4 ? "edge active-edge" : "edge"} d={`M${nodes[a][0]} ${nodes[a][1]} C${nodes[a][0] + 75} ${nodes[a][1]}, ${nodes[b][0] - 75} ${nodes[b][1]}, ${nodes[b][0]} ${nodes[b][1]}`} />)}{nodes.map(([x,y], i) => <circle key={`${x}-${y}`} cx={x} cy={y} r={i === 10 ? 8 : 5} className={i % 4 === active ? "neuron active-neuron" : "neuron"} onClick={() => setActive(i % 4)} />)}</svg><div className="layer-labels"><span>INPUT</span><span>HIDDEN 01</span><span>HIDDEN 02</span><span>OUTPUT</span></div><div className="packet packet-one">{["DATA", "IMAGE", "TEXT", "SIGNAL", "API"][active]}</div></div>; }
function Hero() { return <section id="top" className="hero"><div className="hero-copy"><p className="eyebrow">APPLIED AI / SYSTEMS PROFILE</p><h1>MUKUND<br /><em>GARG</em></h1><p className="hero-lede">Building intelligent systems from data, models and code.</p><p className="hero-meta">ECE @ MSIT · Delhi, India</p><div className="hero-actions"><a className="button coral" href="#work">Explore Systems <ArrowDown /></a><a className="text-link" href={socials.resume} target="_blank" rel="noreferrer">View Resume <ArrowUpRight /></a></div></div><Network /></section>; }
function Graph() { return <div className="knowledge-graph"><svg viewBox="0 0 620 280" role="img" aria-label="Knowledge graph connecting Mukund to machine learning, backend and computer vision"><path d="M310 140H150M310 140H470M310 140V45M310 140V235M150 140V80M470 140V80M470 140V205" className="graph-edge" /><circle cx="310" cy="140" r="24" className="graph-core" /><circle cx="150" cy="140" r="10" className="graph-node" /><circle cx="470" cy="140" r="10" className="graph-node" /><circle cx="310" cy="45" r="10" className="graph-node" /><circle cx="310" cy="235" r="10" className="graph-node" /></svg><span className="graph-name core-name">MUKUND</span><span className="graph-name left-name">BACKEND<br /><small>FastAPI · APIs</small></span><span className="graph-name right-name">MACHINE LEARNING<br /><small>XGBoost · SVM · PCA</small></span><span className="graph-name top-name">COMPUTER VISION<br /><small>OpenCV · CNN</small></span><span className="graph-name bottom-name">NLP<br /><small>Attention · Transformers</small></span></div>; }
function Profile() { return <section id="about" className="section profile-section"><div className="section-head"><span>01 / PROFILE</span><i /></div><div className="profile-grid"><div><h2>From signals<br />to <em>systems.</em></h2><p>I&apos;m an Electronics &amp; Communication Engineering student focused on machine learning, deep learning, computer vision, NLP and backend development.</p><p>I enjoy building end-to-end systems that combine models, APIs, automation and real-world applications.</p></div><Graph /></div></section>; }
function Diagram({ index }: { index: number }) { if (index === 0) return <div className="system-diagram flow-diagram"><span>CSV / SHEETS</span><b>→</b><span>PERSONALIZE</span><b>→</b><span>SCHEDULER</span><b>→</b><span>GMAIL API</span><small>FOLLOW-UP · REPLY CHECK · STATUS SYNC</small></div>; if (index === 1) return <div className="system-diagram chart-diagram"><svg viewBox="0 0 520 170" role="img" aria-label="Illustrative stock pattern chart"><path d="M0 145 C45 115 60 138 92 105 S145 130 176 88 S226 105 260 72 S310 95 344 45 S392 76 430 38 S470 48 520 12" /><path d="M0 155H520M0 85H520M0 15H520" className="chart-grid" /><line x1="344" y1="20" x2="344" y2="160" className="scanner" /></svg><small>ILLUSTRATIVE SIGNAL · PATTERN DETECTION</small></div>; return <div className="system-diagram hand-diagram"><svg viewBox="0 0 520 210" role="img" aria-label="Hand landmark model visualization"><path d="M180 176L166 110 145 62 154 52 181 92 175 24 188 20 207 89 215 8 229 10 234 90 253 28 266 34 257 99 284 63 296 72 260 130 246 178Z" /><path d="M166 110L207 89 234 90 257 99 260 130 246 178" className="hand-edge" />{[[166,110],[145,62],[181,92],[175,24],[207,89],[215,8],[234,90],[253,28],[257,99],[284,63],[260,130],[246,178]].map(([cx,cy]) => <circle key={`${cx}-${cy}`} cx={cx} cy={cy} r="5" />)}</svg><span>CAMERA → VISION MODEL → STABILIZATION → <em>HELLO</em></span></div>; }
function ProjectPost({ project, index }: { project: (typeof projects)[number]; index: number }) { const [open, setOpen] = useState(false); return <motion.article className="project-post" variants={reveal} initial="hidden" whileInView="show" viewport={{ once: true }}><div className="post-meta"><span>SYS-0{index + 1}</span><span>{project.kicker}</span></div><h3>{project.title}</h3><p className="project-description">{project.description}</p><Diagram index={index} /><div className="metric-row">{project.metrics.map((m) => <span key={m}>{m}</span>)}</div><div className="stack-row">{project.stack.map((s) => <span key={s}>{s}</span>)}</div><div className="post-footer"><a href={project.github} target="_blank" rel="noreferrer"><Github /> GitHub <ArrowUpRight /></a>{project.live && <a href={project.live} target="_blank" rel="noreferrer"><ExternalLink /> Live Demo <ArrowUpRight /></a>}{index === 0 && <button onClick={() => setOpen(!open)} aria-expanded={open}><Pin /> {open ? "Close thread" : "Architecture note"}</button>}</div>{open && <div className="thread"><strong>Why I built this</strong><p>MailPilot came directly from repetitive outreach work at Iqlipse. After identifying reliability limits in the existing Mailmeteor workflow, I built a local system for personalized campaigns, scheduling, threaded follow-ups, reply detection, and Sheets sync.</p><code>@app.post("/campaign")<br />async def create_campaign(...):</code></div>}</motion.article>; }
function Systems() { return <section id="work" className="section"><div className="section-head"><span>02 / APPLIED SYSTEMS</span><i /></div><div className="section-intro"><h2>Projects with a<br /><em>reason to exist.</em></h2><p>Concrete problems, connected layers, useful software.</p></div>{projects.map((p,i) => <ProjectPost key={p.title} project={p} index={i} />)}</section>; }
function Experience() { return <section id="experience" className="section experience-section"><div className="section-head"><span>03 / EXPERIENCE</span><i /></div><article className="timeline-item"><div className="timeline-marker" /><div><p className="eyebrow">{experience.period} · {experience.location}</p><h3>{experience.role}</h3><p className="org">{experience.company}</p><ul>{experience.bullets.map((b) => <li key={b}>{b}</li>)}</ul></div></article></section>; }
function Education() { return <section id="education" className="section education-section"><div className="section-head"><span>04 / EDUCATION + LEADERSHIP</span><i /></div><div className="education-layout"><div className="education-list">{education.map((item) => <article key={item.school}><GraduationCap /><div><p className="eyebrow">{item.period}</p><h3>{item.school}</h3><p>{item.degree}</p><strong>{item.meta}</strong></div></article>)}</div><div className="signal-chain">ECE <i>↓</i> SIGNALS <i>↓</i> DATA <i>↓</i> MODELS <i>↓</i> SYSTEMS</div></div><div className="leadership"><p className="eyebrow">LEADERSHIP</p>{leadership.map((item) => <div key={item.org}><strong>{item.role}</strong><span>{item.org}</span><small>{item.period}</small></div>)}</div></section>; }
function Footer() { return <section id="contact" className="contact-section"><div className="converge"><span>AI</span><span>ML</span><span>CODE</span><span>SYSTEMS</span><span>PROJECTS</span><i /></div><p className="eyebrow">05 / CONTACT</p><h2>Have a technical problem<br /><em>worth building around?</em></h2><a className="button coral" href={socials.email}>Let&apos;s connect <ArrowUpRight /></a><footer><span>© 2026 Mukund Garg</span><div><a href={socials.github}><Github /></a><a href={socials.linkedin}><Linkedin /></a><a href={socials.email}><Mail /></a></div></footer></section>; }
export function Portfolio() { return <><Boot /><Trace /><Navbar /><main><Hero /><Profile /><Systems /><Experience /><Education /><Footer /></main></>; }
